### PR TITLE
[WIP] Java 10

### PR DESCRIPTION
**Pull request by AustinShalit**
Start work on getting fresh mark to build on Java 10.

### CODE REVIEW

**Comment by nedtwigg** [comment]
Looks great, thanks @AustinShalit.  I haven't yet ventured past Java 8 myself, but I'll be happy to merge and release when you're ready.

**Comment by AustinShalit** [comment]
Sounds good.  Still need to figure out release publishing (I deleted it from the build.gradle for now).  After that, we need to update spotless to run on Java 9+: https://github.com/diffplug/spotless/issues/206

Once both of those things are done, this should be good to go.

**Comment by nedtwigg** [comment]
Need anything from me @AustinShalit?

**Comment by AustinShalit** [comment]
Nope.  Family stuff popped up.  Should be able to resume work next week.

**Comment by saily** [comment]
What's missing to get this merged?

**Comment by JLLeitschuh** [comment]
Hey @AustinShalit, & @nedtwigg, I just ran headlong into this one as a part of testing my build under JDK 10.
Anything I can do to help on this one?

**Comment by nedtwigg** [comment]
I haven't even peeked at migrating my products to Java 9, let alone 10.  I'm happy to merge and release whatever is needed, but I've got no leadership to offer on this topic.

**Comment by JLLeitschuh** [comment]
@nedtwigg With Oracle EOLing support for JDK 8, it would probably be good to start getting things supporting JDK 10. (Probably not worth doing JDK 9 at this point).

**Comment by AustinShalit** [comment]
It has been over a year and I still do not have time.  Closing this PR.  Hopefully someone can pick it up though.

**Pull request closed without merging**
